### ISSUE TITLE
Instructions on how to generate the .exe file

### ISSUE THREAD

**Issue by patrickjrs** [NicholasDawson/GooglePhotosArchiver#3]
What tool did you use to generate the .exe file? I tried pyinstaller but seems to require some extra configuration. If you used the same tool, did you have to add anything to the .spec file for resolving dependencies?

**Comment by NicholasDawson** [comment]
I used pyinstaller to make the executable, and I believe it was as simple as one command. I used the --onefile flag.

Here's some docs/tutorials that may help you:
https://realpython.com/pyinstaller-python/
https://pyinstaller.readthedocs.io/en/stable/usage.html

**Comment by patrickjrs** [comment]
Thanks, @NicholasDawson. I used the same flag but for some reason, it did not work in my case, maybe an environment issue. I'll dig into the docs a bit more.

**Comment by NicholasDawson** [comment]
Okay, let me know if you want help. I can help you work through it probably if you don't get it. If you email me I can give you my discord or something

**Comment by patrickjrs** [comment]
Thanks man! It's not super urgent, haven't looked at it in a few days, might take another stab at it tomorrow. I'll let you know how it goes.
